### ISSUE TITLE
Fatal error on a table

### ISSUE THREAD

**Issue by DylanDelobel** [vcian/php-db-auditor#12]
PHP8.1 and SF6.3
Here the Slacktrace
```
php vendor/vcian/php-db-auditor/dbauditor db:standard

PHP Fatal error:  Uncaught TypeError: Vcian\PhpDbAuditor\Command\DBStandardCheck::getTableSize(): Return value must be of type string, null returned in /var/www/popcarte/ProjectName/vendor/vcian/php-db-auditor/src/Traits/DBConnection.php:120
Stack trace:
#0 /var/www/popcarte/ProjectName/vendor/vcian/php-db-auditor/src/Traits/Rules.php(30): Vcian\PhpDbAuditor\Command\DBStandardCheck->getTableSize('last_month_orde...')
#1 /var/www/popcarte/ProjectName/vendor/vcian/php-db-auditor/src/Command/DBStandardCheck.php(27): Vcian\PhpDbAuditor\Command\DBStandardCheck->tablesRule()
#2 /var/www/popcarte/ProjectName/vendor/symfony/console/Command/Command.php(326): Vcian\PhpDbAuditor\Command\DBStandardCheck->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/popcarte/ProjectName/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/popcarte/ProjectName/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Vcian\PhpDbAuditor\Command\DBStandardCheck), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/popcarte/ProjectName/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/popcarte/ProjectName/vendor/vcian/php-db-auditor/dbauditor(17): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /var/www/popcarte/ProjectName/vendor/vcian/php-db-auditor/src/Traits/DBConnection.php on line 120
  ```
  
  Here the structure fo this table (this table is a view)
  ```sql
  --
-- Structure for view `last_month_orders_per_country_view`
--

CREATE ALGORITHM = UNDEFINED DEFINER =`dbname`@`localhost` SQL SECURITY DEFINER VIEW `last_month_orders_per_country_view` AS
SELECT `o`.`id`     AS `id`,
       `o`.`otime`  AS `otime`,
       `o`.`ostat`  AS `ostat`,
       `u`.`email`  AS `email`,
       `oi`.`stype` AS `stype`,
       `cu`.`name`  AS `user_country`,
       `cr`.`name`  AS `receiver_country`,
       `o`.`total`  AS `total`,
       `o`.`paidby` AS `paidby`,
       `p`.`name`   AS `name`
FROM (((((((`orders` `o` left join `order_items` `oi` on (`o`.`id` = `oi`.`oid`)) join `receivers_items` `ri`
           on (`oi`.`id` = `ri`.`oid`)) join `receivers` `r` on (`ri`.`rid` = `r`.`id`)) join `users` `u`
         on (`o`.`uid` = `u`.`id`)) left join `countries` `cu`
        on (`u`.`country` = `cu`.`country_code`)) left join `countries` `cr`
       on (`r`.`country` = `cr`.`country_code`)) join `partners` `p` on (`o`.`parid` = `p`.`id`))
WHERE `o`.`ostat` in (1, 2, 4, 6, 10)
  AND `o`.`otime` between last_day(curdate() - interval 2 month) + interval 1 day and last_day(curdate() - interval 1 month) + interval 1 day
GROUP BY `o`.`id``id`;
```

**Comment by ruchit288** [comment]
@DylanDelobel  thanks for posting the issue and apologies for the delay.

Regarding this issue.
- We have fixed some issues related to this.
- However, If the table is a view, the size calculation might not work as expected because views don't have a physical size on disk like regular tables. So we have just skipped the view tables to fix this issue.
